# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4dfa25071042010f1980464d393560ac4a3e8c705a8223d4a414ad2b4d20c58c82ad824fdfe94718ac1c23a734b010c539e6f0b8a2047b664f0503b91c959ef

test:
  secret_key_base: dbb9b5bcdd79d06705b1c2c4ceeaae6d4074ce0f863f3da032e4d98f844222433300d41d322cde0585cfe806a3ed488b9fd66a4720961c78c0688cae8fea26e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
